language: swift
osx_image: xcode9.2
xcode_project: THTiledImageView.xcodeproj
xcode_scheme: THTiledImageView
xcode_sdk: iphonesimulator11.2
sudo: required

env:
  global:
    - PROJECT="ReactorKit.xcodeproj"
    - SCHEME="ReactorKit-Package"
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update

script:
  - xcodebuild -workspace THTiledImageView.xcworkspace -scheme THTiledImageView -configuration Debug -enableCodeCoverage YES -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'THTiledImageView' -X xcodeplist
