language: swift
osx_image: xcode9.2
xcode_project: THTiledImageView.xcodeproj
xcode_scheme: THTiledImageView
xcode_sdk: iphonesimulator11.2

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update

script:
- xcodebuild -workspace THTiledImageView.xcworkspace -scheme THTiledImageView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
