language: objective-c
osx_image: xcode9.2
xcode_project: THTiledImageView.xcodeproj #3
xcode_scheme: THTiledImageView #4
xcode_sdk: iphonesimulator11.2 #5

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.4.2
  - brew update
