language: swift
osx_image: xcode9.2
xcode_project: THTiledImageView.xcodeproj
xcode_scheme: THTiledImageView
xcode_sdk: iphonesimulator11.2

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby-2.4.2
  - brew update

script:
- xcodebuild clean build test -project THTiledImageView.xcodeproj -scheme THTiledImageView
