language: swift
osx_image: xcode9.2
xcode_project: THTiledImageView.xcodeproj
xcode_scheme: THTiledImageView
xcode_sdk: iphonesimulator11.2
sudo: required

env:
  global:
    - PROJECT="ReactorKit.xcodeproj"
    - SCHEME="ReactorKit-Package"
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - brew update
  - bundle install

script:
  - xcodebuild clean build test -workspace THTiledImageView.xcworkspace -scheme THTiledImageView -configuration Debug -destination "platform=iOS Simulator,name=iPhone 10,OS=11.2" -enableCodeCoverage YES -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'THTiledImageView' -X xcodeplist
